when:
  - branch:
      - main
      - master
      # - ${CI_REPO_DEFAULT_BRANCH}
    event: [push, pull_request, manual]

steps:
  - name: build
    image: debian:stable-slim
    commands:
      - echo building
      - echo "Environment:"
      - env
