when:
  - event: [push, pull_request, manual]
    # branch:
    #   - main
    #   - master
    #   # - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: build
    image: debian:stable-slim
    commands:
      - echo building
      - echo "Environment:"
      - env
